export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const EMAIL_NOT_EXISTS = 'EMAIL_NOT_EXISTS';
export const EMAIL_DONT_MATCH = 'EMAIL_DONT_MATCH';

export const BOARD_NOT_FOUND = 'BOARD_NOT_FOUND';
export const BOARDS_NOT_FOUND = 'BOARDS_NOT_FOUND';

export const TOKENS_NOT_MATCHING = 'TOKENS_NOT_MATCHING';

export const UNAUTHORIZED = 'UNAUTHORIZED';
export const UPDATE_FAILED = 'UPDATE_FAILED';
export const DELETE_FAILED = 'DELETE_FAILED';
export const INSERT_FAILED = 'INSERT_FAILED';
