export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const EMAIL_NOT_EXISTS = 'EMAIL_NOT_EXISTS';

export const BOARD_NOT_FOUND = 'BOARD_NOT_FOUND';
export const BOARDS_NOT_FOUND = 'BOARDS_NOT_FOUND';
