#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


rootDir=$PWD

folders=("backend" "frontend")

for folder in "${folders[@]}"
do
	echo "-- ${folder} --"
	cd ${rootDir}/${folder}
	npm run pre-commit
done

# npm run pre-commit